//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------

namespace CCFlow.WF.Rpt {
    
    
    public partial class SearchAdv {
        
        /// <summary>
        /// Pub1  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::CCFlow.WF.Pub Pub1;
        
        /// <summary>
        /// Pub2  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::CCFlow.WF.Pub Pub2;
        
        /// <summary>
        /// hiddenAttrKey  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hiddenAttrKey;
        
        /// <summary>
        /// btnSearch  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::BP.Web.Controls.LinkBtn btnSearch;
        
        /// <summary>
        /// btnSaveSearchDirect  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::BP.Web.Controls.LinkBtn btnSaveSearchDirect;
        
        /// <summary>
        /// btnSaveSearch  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor btnSaveSearch;
        
        /// <summary>
        /// btnDeleteModel  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::BP.Web.Controls.LinkBtn btnDeleteModel;
        
        /// <summary>
        /// btnExport  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::BP.Web.Controls.LinkBtn btnExport;
        
        /// <summary>
        /// LB_Attrs  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::BP.Web.Controls.LB LB_Attrs;
        
        /// <summary>
        /// btnOK  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::BP.Web.Controls.LinkBtn btnOK;
        
        /// <summary>
        /// TB_SearchName  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::BP.Web.Controls.TB TB_SearchName;
        
        /// <summary>
        /// btnSaveSearchOK  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::BP.Web.Controls.LinkBtn btnSaveSearchOK;
        
        /// <summary>
        /// UCSys1  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::CCFlow.WF.Comm.UC.UCSys UCSys1;
        
        /// <summary>
        /// Pub3  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::CCFlow.WF.Pub Pub3;
    }
}
