//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------



public partial class CCFlow_Comm_HelperOfTBNum {
    
    /// <summary>
    /// form1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    /// <summary>
    /// UcTitle  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::CCFlow.WF.Comm.UC.UCSys UcTitle;
    
    /// <summary>
    /// TextBox1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox TextBox1;
    
    /// <summary>
    /// DropDownList1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
    
    /// <summary>
    /// Button1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button Button1;
    
    /// <summary>
    /// Ucsys1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::CCFlow.WF.Comm.UC.UCSys Ucsys1;
    
    /// <summary>
    /// Ucsys2  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::CCFlow.WF.Comm.UC.UCSys Ucsys2;
}
