//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM.ERPWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SPR", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SPR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERP_SPR_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status_Updated_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Execution_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ERP_SPR_ID {
            get {
                return this.ERP_SPR_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.ERP_SPR_IDField, value) != true)) {
                    this.ERP_SPR_IDField = value;
                    this.RaisePropertyChanged("ERP_SPR_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status_Updated_Date {
            get {
                return this.Status_Updated_DateField;
            }
            set {
                if ((object.ReferenceEquals(this.Status_Updated_DateField, value) != true)) {
                    this.Status_Updated_DateField = value;
                    this.RaisePropertyChanged("Status_Updated_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Execution_Date {
            get {
                return this.Execution_DateField;
            }
            set {
                if ((object.ReferenceEquals(this.Execution_DateField, value) != true)) {
                    this.Execution_DateField = value;
                    this.RaisePropertyChanged("Execution_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PaymentRef {
            get {
                return this.PaymentRefField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentRefField, value) != true)) {
                    this.PaymentRefField = value;
                    this.RaisePropertyChanged("PaymentRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ERPWebService.ERPWebServiceSoap")]
    public interface ERPWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name SAM_SPR_ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewSPR", ReplyAction="*")]
        SAM.ERPWebService.CreateNewSPRResponse CreateNewSPR(SAM.ERPWebService.CreateNewSPRRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewSPRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewSPR", Namespace="http://tempuri.org/", Order=0)]
        public SAM.ERPWebService.CreateNewSPRRequestBody Body;
        
        public CreateNewSPRRequest() {
        }
        
        public CreateNewSPRRequest(SAM.ERPWebService.CreateNewSPRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNewSPRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SAM_SPR_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SPR_Type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Requested_By;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Supplier_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Ammount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Request_Date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Due_Date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Site_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SAM_Contract_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SAM_Contract_Summary;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Comment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Payment_Validity_From;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Payment_Validity_To;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Analytical_Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Supplier_Acc_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Supplier_Acc_Bank;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Supplier_ACC_SHEBA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Supplier_Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Site_Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Approved_By;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Reviewed_By;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Initiated_By;
        
        public CreateNewSPRRequestBody() {
        }
        
        public CreateNewSPRRequestBody(
                    string SAM_SPR_ID, 
                    string SPR_Type, 
                    string Requested_By, 
                    string Supplier_ID, 
                    string Ammount, 
                    string Request_Date, 
                    string Due_Date, 
                    string Site_ID, 
                    string SAM_Contract_ID, 
                    string SAM_Contract_Summary, 
                    string Comment, 
                    string Payment_Validity_From, 
                    string Payment_Validity_To, 
                    string Analytical_Account, 
                    string Supplier_Acc_NO, 
                    string Supplier_Acc_Bank, 
                    string Supplier_ACC_SHEBA, 
                    string Supplier_Address, 
                    string Site_Address, 
                    string Approved_By, 
                    string Reviewed_By, 
                    string Initiated_By) {
            this.SAM_SPR_ID = SAM_SPR_ID;
            this.SPR_Type = SPR_Type;
            this.Requested_By = Requested_By;
            this.Supplier_ID = Supplier_ID;
            this.Ammount = Ammount;
            this.Request_Date = Request_Date;
            this.Due_Date = Due_Date;
            this.Site_ID = Site_ID;
            this.SAM_Contract_ID = SAM_Contract_ID;
            this.SAM_Contract_Summary = SAM_Contract_Summary;
            this.Comment = Comment;
            this.Payment_Validity_From = Payment_Validity_From;
            this.Payment_Validity_To = Payment_Validity_To;
            this.Analytical_Account = Analytical_Account;
            this.Supplier_Acc_NO = Supplier_Acc_NO;
            this.Supplier_Acc_Bank = Supplier_Acc_Bank;
            this.Supplier_ACC_SHEBA = Supplier_ACC_SHEBA;
            this.Supplier_Address = Supplier_Address;
            this.Site_Address = Site_Address;
            this.Approved_By = Approved_By;
            this.Reviewed_By = Reviewed_By;
            this.Initiated_By = Initiated_By;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewSPRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewSPRResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAM.ERPWebService.CreateNewSPRResponseBody Body;
        
        public CreateNewSPRResponse() {
        }
        
        public CreateNewSPRResponse(SAM.ERPWebService.CreateNewSPRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNewSPRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SAM.ERPWebService.SPR CreateNewSPRResult;
        
        public CreateNewSPRResponseBody() {
        }
        
        public CreateNewSPRResponseBody(SAM.ERPWebService.SPR CreateNewSPRResult) {
            this.CreateNewSPRResult = CreateNewSPRResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ERPWebServiceSoapChannel : SAM.ERPWebService.ERPWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERPWebServiceSoapClient : System.ServiceModel.ClientBase<SAM.ERPWebService.ERPWebServiceSoap>, SAM.ERPWebService.ERPWebServiceSoap {
        
        public ERPWebServiceSoapClient() {
        }
        
        public ERPWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ERPWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAM.ERPWebService.CreateNewSPRResponse SAM.ERPWebService.ERPWebServiceSoap.CreateNewSPR(SAM.ERPWebService.CreateNewSPRRequest request) {
            return base.Channel.CreateNewSPR(request);
        }
        
        public SAM.ERPWebService.SPR CreateNewSPR(
                    string SAM_SPR_ID, 
                    string SPR_Type, 
                    string Requested_By, 
                    string Supplier_ID, 
                    string Ammount, 
                    string Request_Date, 
                    string Due_Date, 
                    string Site_ID, 
                    string SAM_Contract_ID, 
                    string SAM_Contract_Summary, 
                    string Comment, 
                    string Payment_Validity_From, 
                    string Payment_Validity_To, 
                    string Analytical_Account, 
                    string Supplier_Acc_NO, 
                    string Supplier_Acc_Bank, 
                    string Supplier_ACC_SHEBA, 
                    string Supplier_Address, 
                    string Site_Address, 
                    string Approved_By, 
                    string Reviewed_By, 
                    string Initiated_By) {
            SAM.ERPWebService.CreateNewSPRRequest inValue = new SAM.ERPWebService.CreateNewSPRRequest();
            inValue.Body = new SAM.ERPWebService.CreateNewSPRRequestBody();
            inValue.Body.SAM_SPR_ID = SAM_SPR_ID;
            inValue.Body.SPR_Type = SPR_Type;
            inValue.Body.Requested_By = Requested_By;
            inValue.Body.Supplier_ID = Supplier_ID;
            inValue.Body.Ammount = Ammount;
            inValue.Body.Request_Date = Request_Date;
            inValue.Body.Due_Date = Due_Date;
            inValue.Body.Site_ID = Site_ID;
            inValue.Body.SAM_Contract_ID = SAM_Contract_ID;
            inValue.Body.SAM_Contract_Summary = SAM_Contract_Summary;
            inValue.Body.Comment = Comment;
            inValue.Body.Payment_Validity_From = Payment_Validity_From;
            inValue.Body.Payment_Validity_To = Payment_Validity_To;
            inValue.Body.Analytical_Account = Analytical_Account;
            inValue.Body.Supplier_Acc_NO = Supplier_Acc_NO;
            inValue.Body.Supplier_Acc_Bank = Supplier_Acc_Bank;
            inValue.Body.Supplier_ACC_SHEBA = Supplier_ACC_SHEBA;
            inValue.Body.Supplier_Address = Supplier_Address;
            inValue.Body.Site_Address = Site_Address;
            inValue.Body.Approved_By = Approved_By;
            inValue.Body.Reviewed_By = Reviewed_By;
            inValue.Body.Initiated_By = Initiated_By;
            SAM.ERPWebService.CreateNewSPRResponse retVal = ((SAM.ERPWebService.ERPWebServiceSoap)(this)).CreateNewSPR(inValue);
            return retVal.Body.CreateNewSPRResult;
        }
    }
}
