//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------

namespace CCFlow.SDKFlowDemo.SDK.F111 {
    
    
    public partial class S11101 {
        
        /// <summary>
        /// DocRelease1  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::CCFlow.SDKFlowDemo.SDK.F111.DocRelease DocRelease1;
    }
}
