//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------



public partial class CCFlow_Comm_UC_UIEn {
    
    /// <summary>
    /// ToolBar1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::CCFlow.WF.Comm.UC.ToolBar ToolBar1;
    
    /// <summary>
    /// UCEn1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::CCFlow.Web.Comm.UC.UCEn UCEn1;
}
