//------------------------------------------------------------------------------
// <auto-generated>
//      This code is generated by the tool .
//      Runtime version :4.0.30319.296
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost .
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.AAA {

    using System;
    
    
    /// <summary>
    ///    A strongly typed resource class , Used to find localized strings, etc. .
    /// </summary>
    //  Such is the  StronglyTypedResourceBuilder
    //  Classes like  ResGen 或 Visual Studio  The tool automatically generates the .
    //  To add or remove members , Please edit  .ResX  File , Then re-run  ResGen
    // (以 /str  As the command options ), Or rebuild  VS  Project .
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///    Return to such use of cache  ResourceManager  Examples .
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BP.AAA.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Use this strongly typed resource class , Find resources for all 
        ///    Rewrite the current thread  CurrentUICulture  Property .
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Find Similar  Add Direction  Localized string .
        /// </summary>
        public static string Button_AddDirection {
            get {
                return ResourceManager.GetString("Button_AddDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Add FlowNode  Localized string .
        /// </summary>
        public static string Button_AddFlowNode {
            get {
                return ResourceManager.GetString("Button_AddFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Add Label  Localized string .
        /// </summary>
        public static string Button_AddLabel {
            get {
                return ResourceManager.GetString("Button_AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  AddTemplate  Localized string .
        /// </summary>
        public static string Button_AddTemplate {
            get {
                return ResourceManager.GetString("Button_AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Apply  Localized string .
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Cancle  Localized string .
        /// </summary>
        public static string Button_Cancle {
            get {
                return ResourceManager.GetString("Button_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Clear  Localized string .
        /// </summary>
        public static string Button_ClearContainer {
            get {
                return ResourceManager.GetString("Button_ClearContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Close  Localized string .
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  CreatePicture  Localized string .
        /// </summary>
        public static string Button_CreatePicture {
            get {
                return ResourceManager.GetString("Button_CreatePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  CreatTemplate  Localized string .
        /// </summary>
        public static string Button_CreatTemplate {
            get {
                return ResourceManager.GetString("Button_CreatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Delete  Localized string .
        /// </summary>
        public static string Button_DelFlow {
            get {
                return ResourceManager.GetString("Button_DelFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  DesignerTable  Localized string .
        /// </summary>
        public static string Button_DesignerTable {
            get {
                return ResourceManager.GetString("Button_DesignerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Edit  Localized string .
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Export  Localized string .
        /// </summary>
        public static string Button_ExportToXml {
            get {
                return ResourceManager.GetString("Button_ExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  FlowCheck  Localized string .
        /// </summary>
        public static string Button_FlowCheck {
            get {
                return ResourceManager.GetString("Button_FlowCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  FlowProper  Localized string .
        /// </summary>
        public static string Button_FlowProper {
            get {
                return ResourceManager.GetString("Button_FlowProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  FlowRptDefinition  Localized string .
        /// </summary>
        public static string Button_FlowRptDefinition {
            get {
                return ResourceManager.GetString("Button_FlowRptDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Import  Localized string .
        /// </summary>
        public static string Button_ImportFromXml {
            get {
                return ResourceManager.GetString("Button_ImportFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  NewFlow  Localized string .
        /// </summary>
        public static string Button_NewFlow {
            get {
                return ResourceManager.GetString("Button_NewFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Next  Localized string .
        /// </summary>
        public static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  OK  Localized string .
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Previous  Localized string .
        /// </summary>
        public static string Button_Previous {
            get {
                return ResourceManager.GetString("Button_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  RunFlow  Localized string .
        /// </summary>
        public static string Button_RunFlow {
            get {
                return ResourceManager.GetString("Button_RunFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Save  Localized string .
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  ShowLine  Localized string .
        /// </summary>
        public static string Button_ShowLine {
            get {
                return ResourceManager.GetString("Button_ShowLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Zoom  Localized string .
        /// </summary>
        public static string Button_Zoom {
            get {
                return ResourceManager.GetString("Button_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  will delete Object,continue?  Localized string .
        /// </summary>
        public static string Comfirm_Delete {
            get {
                return ResourceManager.GetString("Comfirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Height  Localized string .
        /// </summary>
        public static string ContainerHeight {
            get {
                return ResourceManager.GetString("ContainerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Width  Localized string .
        /// </summary>
        public static string ContainerWidth {
            get {
                return ResourceManager.GetString("ContainerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  will delete WorkFlow,continue?  Localized string .
        /// </summary>
        public static string DeleteFlow {
            get {
                return ResourceManager.GetString("DeleteFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  will delete WorkFlow Sort,continue?  Localized string .
        /// </summary>
        public static string DeleteFlowSort {
            get {
                return ResourceManager.GetString("DeleteFlowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Conditon  Localized string .
        /// </summary>
        public static string DirectionCondition {
            get {
                return ResourceManager.GetString("DirectionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Line  Localized string .
        /// </summary>
        public static string DirectionLineType_Line {
            get {
                return ResourceManager.GetString("DirectionLineType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Polyline  Localized string .
        /// </summary>
        public static string DirectionLineType_Polyline {
            get {
                return ResourceManager.GetString("DirectionLineType_Polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Name  Localized string .
        /// </summary>
        public static string DirectionName {
            get {
                return ResourceManager.GetString("DirectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Name  Localized string .
        /// </summary>
        public static string FlowNodeName {
            get {
                return ResourceManager.GetString("FlowNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Type  Localized string .
        /// </summary>
        public static string FlowNodeType {
            get {
                return ResourceManager.GetString("FlowNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  AND_BRANCH  Localized string .
        /// </summary>
        public static string FlowNodeType_AND_BRANCH {
            get {
                return ResourceManager.GetString("FlowNodeType_AND_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  AND_MERGE  Localized string .
        /// </summary>
        public static string FlowNodeType_AND_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_AND_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  AUTOMATION  Localized string .
        /// </summary>
        public static string FlowNodeType_AUTOMATION {
            get {
                return ResourceManager.GetString("FlowNodeType_AUTOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  COMPLETION  Localized string .
        /// </summary>
        public static string FlowNodeType_COMPLETION {
            get {
                return ResourceManager.GetString("FlowNodeType_COMPLETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  DUMMY  Localized string .
        /// </summary>
        public static string FlowNodeType_DUMMY {
            get {
                return ResourceManager.GetString("FlowNodeType_DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  INITIAL  Localized string .
        /// </summary>
        public static string FlowNodeType_INITIAL {
            get {
                return ResourceManager.GetString("FlowNodeType_INITIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  INTERACTION  Localized string .
        /// </summary>
        public static string FlowNodeType_INTERACTION {
            get {
                return ResourceManager.GetString("FlowNodeType_INTERACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  OR_BRANCH  Localized string .
        /// </summary>
        public static string FlowNodeType_OR_BRANCH {
            get {
                return ResourceManager.GetString("FlowNodeType_OR_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  OR_MERGE  Localized string .
        /// </summary>
        public static string FlowNodeType_OR_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_OR_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  SUBPROCESS  Localized string .
        /// </summary>
        public static string FlowNodeType_SUBPROCESS {
            get {
                return ResourceManager.GetString("FlowNodeType_SUBPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  VOTE_MERGE  Localized string .
        /// </summary>
        public static string FlowNodeType_VOTE_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_VOTE_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Is Save ?  Localized string .
        /// </summary>
        public static string IsSave {
            get {
                return ResourceManager.GetString("IsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Type  Localized string .
        /// </summary>
        public static string LineType {
            get {
                return ResourceManager.GetString("LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  AlignBottom  Localized string .
        /// </summary>
        public static string Menu_AlignBottom {
            get {
                return ResourceManager.GetString("Menu_AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  AlignLeft  Localized string .
        /// </summary>
        public static string Menu_AlignLeft {
            get {
                return ResourceManager.GetString("Menu_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  AlignRight  Localized string .
        /// </summary>
        public static string Menu_AlignRight {
            get {
                return ResourceManager.GetString("Menu_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  AlignTop  Localized string .
        /// </summary>
        public static string Menu_AlignTop {
            get {
                return ResourceManager.GetString("Menu_AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Copy  Localized string .
        /// </summary>
        public static string Menu_CopyDirection {
            get {
                return ResourceManager.GetString("Menu_CopyDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Copy  Localized string .
        /// </summary>
        public static string Menu_CopyFlowNode {
            get {
                return ResourceManager.GetString("Menu_CopyFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Copy  Localized string .
        /// </summary>
        public static string Menu_CopyLabel {
            get {
                return ResourceManager.GetString("Menu_CopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Copy  Localized string .
        /// </summary>
        public static string Menu_CopySelected {
            get {
                return ResourceManager.GetString("Menu_CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Delete  Localized string .
        /// </summary>
        public static string Menu_DeleteDirection {
            get {
                return ResourceManager.GetString("Menu_DeleteDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Delete  Localized string .
        /// </summary>
        public static string Menu_DeleteFlowNode {
            get {
                return ResourceManager.GetString("Menu_DeleteFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Delete  Localized string .
        /// </summary>
        public static string Menu_DeleteLabel {
            get {
                return ResourceManager.GetString("Menu_DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Delete  Localized string .
        /// </summary>
        public static string Menu_DeleteSelected {
            get {
                return ResourceManager.GetString("Menu_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Modify  Localized string .
        /// </summary>
        public static string Menu_ModifyDirection {
            get {
                return ResourceManager.GetString("Menu_ModifyDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Modify  Localized string .
        /// </summary>
        public static string Menu_ModifyFlowNode {
            get {
                return ResourceManager.GetString("Menu_ModifyFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Paste  Localized string .
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  ShowGridLines  Localized string .
        /// </summary>
        public static string Menu_ShowGridLines {
            get {
                return ResourceManager.GetString("Menu_ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  begin-activitity can not have pre-FlowNode.  Localized string .
        /// </summary>
        public static string Message_BeginActivitiesCanNotHavePreFlowNode {
            get {
                return ResourceManager.GetString("Message_BeginActivitiesCanNotHavePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  begin and end FlowNode  can not be the same.  Localized string .
        /// </summary>
        public static string Message_BeginAndEndFlowNodeCanNotBeTheSame {
            get {
                return ResourceManager.GetString("Message_BeginAndEndFlowNodeCanNotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  can not have pre-FlowNode.  Localized string .
        /// </summary>
        public static string Message_CanNotHavePreFlowNode {
            get {
                return ResourceManager.GetString("Message_CanNotHavePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  end-activitity can not have follow-up activitiy.  Localized string .
        /// </summary>
        public static string Message_EndFlowNodeCanNotHaveFollowUpActivitiy {
            get {
                return ResourceManager.GetString("Message_EndFlowNodeCanNotHaveFollowUpActivitiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  branch-FlowNode only have one pre-FlowNode.  Localized string .
        /// </summary>
        public static string Message_HeLiuNodeOnlyHaveOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_HeLiuNodeOnlyHaveOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  please modify workflow  in accordance with tips.  Localized string .
        /// </summary>
        public static string Message_ModifyWorkFlowByTip {
            get {
                return ResourceManager.GetString("Message_ModifyWorkFlowByTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  rule must be linked to begin-activitiy and end-FlowNode.  Localized string .
        /// </summary>
        public static string Message_MustBeLinkToBeginAndEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToBeginAndEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  rule must be linked to begin-activitiy.  Localized string .
        /// </summary>
        public static string Message_MustBeLinkToBeginFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToBeginFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  rule must be linked to end-activitiy.  Localized string .
        /// </summary>
        public static string Message_MustBeLinkToEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  must have at least one end-FlowNode.  Localized string .
        /// </summary>
        public static string Message_MustHaveAtLeastOneEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOneEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  must have at least one follow-up FlowNode.  Localized string .
        /// </summary>
        public static string Message_MustHaveAtLeastOneFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOneFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  must have at least one pre-FlowNode.  Localized string .
        /// </summary>
        public static string Message_MustHaveAtLeastOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  must have only one begin-FlowNode.  Localized string .
        /// </summary>
        public static string Message_MustHaveOnlyOneBeginFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOneBeginFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  must have only one follow-up FlowNode  Localized string .
        /// </summary>
        public static string Message_MustHaveOnlyOneFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOneFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  must have only one pre-FlowNode.  Localized string .
        /// </summary>
        public static string Message_MustHaveOnlyOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  not have follow-up FlowNode.  Localized string .
        /// </summary>
        public static string Message_NotHaveFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_NotHaveFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  require the installation of pre-and follow-up activities.  Localized string .
        /// </summary>
        public static string Message_RequireTheInstallationOfPreAndFollowupFlowNode {
            get {
                return ResourceManager.GetString("Message_RequireTheInstallationOfPreAndFollowupFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  WorkFlow had saved!  Localized string .
        /// </summary>
        public static string Message_Saved {
            get {
                return ResourceManager.GetString("Message_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  merge-activitity  only have one follow-up activitiy.  Localized string .
        /// </summary>
        public static string Message_SubThreadNodeOnlyHaveAFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_SubThreadNodeOnlyHaveAFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  The same rule that already exists.  Localized string .
        /// </summary>
        public static string Message_TheSameDirectionThatAlreadyExist {
            get {
                return ResourceManager.GetString("Message_TheSameDirectionThatAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  NewDirection  Localized string .
        /// </summary>
        public static string NewDirection {
            get {
                return ResourceManager.GetString("NewDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  NewFlowNode  Localized string .
        /// </summary>
        public static string NewFlowNode {
            get {
                return ResourceManager.GetString("NewFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  NewFowSort  Localized string .
        /// </summary>
        public static string NewFlowSort {
            get {
                return ResourceManager.GetString("NewFlowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  NewLabel  Localized string .
        /// </summary>
        public static string NewLable {
            get {
                return ResourceManager.GetString("NewLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  OpenFlow  Localized string .
        /// </summary>
        public static string OpenFlow {
            get {
                return ResourceManager.GetString("OpenFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Refresh  Localized string .
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Direction  Localized string .
        /// </summary>
        public static string RepeatDirection {
            get {
                return ResourceManager.GetString("RepeatDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Horizontal  Localized string .
        /// </summary>
        public static string RepeatDirection_Horizontal {
            get {
                return ResourceManager.GetString("RepeatDirection_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Vertical  Localized string .
        /// </summary>
        public static string RepeatDirection_Vertical {
            get {
                return ResourceManager.GetString("RepeatDirection_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  SubFlow  Localized string .
        /// </summary>
        public static string SubFlow {
            get {
                return ResourceManager.GetString("SubFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Dept  Localized string .
        /// </summary>
        public static string TbDept {
            get {
                return ResourceManager.GetString("TbDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Flow  Localized string .
        /// </summary>
        public static string TbItemFlow {
            get {
                return ResourceManager.GetString("TbItemFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Station  Localized string .
        /// </summary>
        public static string TbStation {
            get {
                return ResourceManager.GetString("TbStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Modify  Localized string .
        /// </summary>
        public static string UpdateLable {
            get {
                return ResourceManager.GetString("UpdateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Find Similar  Name  Localized string .
        /// </summary>
        public static string WorkFlowName {
            get {
                return ResourceManager.GetString("WorkFlowName", resourceCulture);
            }
        }
    }
}
