//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------



public partial class WF_MapDef_UC_MExt {
    
    /// <summary>
    /// Left  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::WF_MapDef_Pub Left;
    
    /// <summary>
    /// Pub2  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::WF_MapDef_Pub Pub2;
}
