//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Label", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        internal static string Blank_Text {
            get {
                return ResourceManager.GetString("Blank.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed_Text {
            get {
                return ResourceManager.GetString("Completed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ( Logic ).
        /// </summary>
        internal static string DeleteLogic_Text {
            get {
                return ResourceManager.GetString("DeleteLogic.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Draft_Text {
            get {
                return ResourceManager.GetString("Draft.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string EndTime_Text {
            get {
                return ResourceManager.GetString("EndTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        internal static string Explanation_Text {
            get {
                return ResourceManager.GetString("Explanation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding ( Transfer ).
        /// </summary>
        internal static string ForwardingTransfer_Text {
            get {
                return ResourceManager.GetString("ForwardingTransfer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string Freeze_Text {
            get {
                return ResourceManager.GetString("Freeze.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function execution.
        /// </summary>
        internal static string FunctionExecution_Text {
            get {
                return ResourceManager.GetString("FunctionExecution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyWord.
        /// </summary>
        internal static string KeyWord_Text {
            get {
                return ResourceManager.GetString("KeyWord.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password_Text {
            get {
                return ResourceManager.GetString("Password.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending_Text {
            get {
                return ResourceManager.GetString("Pending.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus sign.
        /// </summary>
        internal static string PlusSign_Text {
            get {
                return ResourceManager.GetString("PlusSign.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return_Text {
            get {
                return ResourceManager.GetString("Return.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run_Text {
            get {
                return ResourceManager.GetString("Run.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string StartTime_Text {
            get {
                return ResourceManager.GetString("StartTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status_Text {
            get {
                return ResourceManager.GetString("Status.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Transfer_Text {
            get {
                return ResourceManager.GetString("Transfer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type_Text {
            get {
                return ResourceManager.GetString("Type.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username_Text {
            get {
                return ResourceManager.GetString("Username.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole.
        /// </summary>
        internal static string Whole_Text {
            get {
                return ResourceManager.GetString("Whole.Text", resourceCulture);
            }
        }
    }
}
