//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Link {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Link() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Link", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AllotTask_Text {
            get {
                return ResourceManager.GetString("AllotTask.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch launched.
        /// </summary>
        internal static string BatchLaunched_Text {
            get {
                return ResourceManager.GetString("BatchLaunched.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out.
        /// </summary>
        internal static string CheckOut_Text {
            get {
                return ResourceManager.GetString("CheckOut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click pending execution process.
        /// </summary>
        internal static string ClickPendingExecutionProcess_Text {
            get {
                return ResourceManager.GetString("ClickPendingExecutionProcess.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the delete process.
        /// </summary>
        internal static string ClickTheDeleteProcess_Text {
            get {
                return ResourceManager.GetString("ClickTheDeleteProcess.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to cancel the pending execution process.
        /// </summary>
        internal static string ClickToCancelThePendingExecutionProcess_Text {
            get {
                return ResourceManager.GetString("ClickToCancelThePendingExecutionProcess.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to perform the recovery process.
        /// </summary>
        internal static string ClickToPerformTheRecoveryProcess_Text {
            get {
                return ResourceManager.GetString("ClickToPerformTheRecoveryProcess.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to retrieve the approval process execution.
        /// </summary>
        internal static string ClickToRetrieveTheApprovalProcessExecution_Text {
            get {
                return ResourceManager.GetString("ClickToRetrieveTheApprovalProcessExecution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_Text {
            get {
                return ResourceManager.GetString("Delete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch.
        /// </summary>
        internal static string Dispatch_Text {
            get {
                return ResourceManager.GetString("Dispatch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bbs.ccflow.org.
        /// </summary>
        internal static string forum_Href {
            get {
                return ResourceManager.GetString("forum.Href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ccflow  Technology Forum.
        /// </summary>
        internal static string forum_Text {
            get {
                return ResourceManager.GetString("forum.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        internal static string Jump_Text {
            get {
                return ResourceManager.GetString("Jump.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the application log ....
        /// </summary>
        internal static string loginApp_Text {
            get {
                return ResourceManager.GetString("loginApp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into the blog mode ....
        /// </summary>
        internal static string loginBlog_Text {
            get {
                return ResourceManager.GetString("loginBlog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Into the Process Designer ( Normal mode )....
        /// </summary>
        internal static string loginNormal_Text {
            get {
                return ResourceManager.GetString("loginNormal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Into the Process Designer (&lt;font color=&quot;red&quot;&gt; Upgrade Mode &lt;/font&gt;, Will not affect your data )....
        /// </summary>
        internal static string loginUpdate_Text {
            get {
                return ResourceManager.GetString("loginUpdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout_Text {
            get {
                return ResourceManager.GetString("Logout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Process.
        /// </summary>
        internal static string NewProcess_Text {
            get {
                return ResourceManager.GetString("NewProcess.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        internal static string Rollback_Text {
            get {
                return ResourceManager.GetString("Rollback.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work trajectory.
        /// </summary>
        internal static string Rpt_Text {
            get {
                return ResourceManager.GetString("Rpt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on.
        /// </summary>
        internal static string TurnOn_Text {
            get {
                return ResourceManager.GetString("TurnOn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revocation of this transmission.
        /// </summary>
        internal static string UnDo_Text {
            get {
                return ResourceManager.GetString("UnDo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ccflow.org.
        /// </summary>
        internal static string website_Href {
            get {
                return ResourceManager.GetString("website.Href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ccflow  Official Website.
        /// </summary>
        internal static string website_Text {
            get {
                return ResourceManager.GetString("website.Text", resourceCulture);
            }
        }
    }
}
