//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Menu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Accessories.
        /// </summary>
        internal static string Ath_Text {
            get {
                return ResourceManager.GetString("Ath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        internal static string Batch_Text {
            get {
                return ResourceManager.GetString("Batch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc.
        /// </summary>
        internal static string Cc_Text {
            get {
                return ResourceManager.GetString("Cc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajectories.
        /// </summary>
        internal static string ChartTrack_Text {
            get {
                return ResourceManager.GetString("ChartTrack.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts_Text {
            get {
                return ResourceManager.GetString("Contacts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalization.
        /// </summary>
        internal static string Globalization_Text {
            get {
                return ResourceManager.GetString("Globalization.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string Inquiry_Text {
            get {
                return ResourceManager.GetString("Inquiry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In transit.
        /// </summary>
        internal static string InTransit_Text {
            get {
                return ResourceManager.GetString("InTransit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Search.
        /// </summary>
        internal static string KeywordSearch_Text {
            get {
                return ResourceManager.GetString("KeywordSearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch(Tree).
        /// </summary>
        internal static string LaunchTree_Text {
            get {
                return ResourceManager.GetString("LaunchTree.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        internal static string Launch_Text {
            get {
                return ResourceManager.GetString("Launch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance duties.
        /// </summary>
        internal static string MaintenanceDuties_Text {
            get {
                return ResourceManager.GetString("MaintenanceDuties.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating.
        /// </summary>
        internal static string OP_Text {
            get {
                return ResourceManager.GetString("OP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Structure.
        /// </summary>
        internal static string OrganizationalStructure_Text {
            get {
                return ResourceManager.GetString("OrganizationalStructure.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending_Text {
            get {
                return ResourceManager.GetString("Pending.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Type.
        /// </summary>
        internal static string PostType_Text {
            get {
                return ResourceManager.GetString("PostType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Post_Text {
            get {
                return ResourceManager.GetString("Post.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Scheduling.
        /// </summary>
        internal static string ProcessScheduling_Text {
            get {
                return ResourceManager.GetString("ProcessScheduling.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve approval.
        /// </summary>
        internal static string RetrieveApproval_Text {
            get {
                return ResourceManager.GetString("RetrieveApproval.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Type.
        /// </summary>
        internal static string SectorType_Text {
            get {
                return ResourceManager.GetString("SectorType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up.
        /// </summary>
        internal static string Setup_Text {
            get {
                return ResourceManager.GetString("Setup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared mission.
        /// </summary>
        internal static string SharedMission_Text {
            get {
                return ResourceManager.GetString("SharedMission.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Messages.
        /// </summary>
        internal static string SystemMessages_Text {
            get {
                return ResourceManager.GetString("SystemMessages.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Logs.
        /// </summary>
        internal static string Track_Text {
            get {
                return ResourceManager.GetString("Track.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string Upcoming_Text {
            get {
                return ResourceManager.GetString("Upcoming.Text", resourceCulture);
            }
        }
    }
}
