//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Title", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string Accepted_Text {
            get {
                return ResourceManager.GetString("Accepted.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string Activity_Text {
            get {
                return ResourceManager.GetString("Activity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annex No.
        /// </summary>
        internal static string AnnexNo_Text {
            get {
                return ResourceManager.GetString("AnnexNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time.
        /// </summary>
        internal static string ArrivalTime_Text {
            get {
                return ResourceManager.GetString("ArrivalTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch launched.
        /// </summary>
        internal static string BatchLaunched_Text {
            get {
                return ResourceManager.GetString("BatchLaunched.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jinan gallop IT Ltd.  @2003-2013.
        /// </summary>
        internal static string co_Text {
            get {
                return ResourceManager.GetString("co.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current node.
        /// </summary>
        internal static string CurrentNode_Text {
            get {
                return ResourceManager.GetString("CurrentNode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date_Text {
            get {
                return ResourceManager.GetString("Date.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Process.
        /// </summary>
        internal static string DeleteProcess_Text {
            get {
                return ResourceManager.GetString("DeleteProcess.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        internal static string DepartmentName_Text {
            get {
                return ResourceManager.GetString("DepartmentName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description_Text {
            get {
                return ResourceManager.GetString("Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email_Text {
            get {
                return ResourceManager.GetString("Email.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling data recovery process to the end node.
        /// </summary>
        internal static string EnablingDataRecoveryProcessToTheEndNode_Text {
            get {
                return ResourceManager.GetString("EnablingDataRecoveryProcessToTheEndNode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor.
        /// </summary>
        internal static string Executor_Text {
            get {
                return ResourceManager.GetString("Executor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature List.
        /// </summary>
        internal static string FeatureList_Text {
            get {
                return ResourceManager.GetString("FeatureList.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow chart.
        /// </summary>
        internal static string FlowChart_Text {
            get {
                return ResourceManager.GetString("FlowChart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced transfer.
        /// </summary>
        internal static string ForcedTransfer_Text {
            get {
                return ResourceManager.GetString("ForcedTransfer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form_Text {
            get {
                return ResourceManager.GetString("Form.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ccflow  Technology Forum.
        /// </summary>
        internal static string forum_Text {
            get {
                return ResourceManager.GetString("forum.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From node.
        /// </summary>
        internal static string FromNode_Text {
            get {
                return ResourceManager.GetString("FromNode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string Function_Text {
            get {
                return ResourceManager.GetString("Function.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History launched.
        /// </summary>
        internal static string HistoryLaunched_Text {
            get {
                return ResourceManager.GetString("HistoryLaunched.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home_Text {
            get {
                return ResourceManager.GetString("Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID_Text {
            get {
                return ResourceManager.GetString("ID.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information_Text {
            get {
                return ResourceManager.GetString("Information.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch date.
        /// </summary>
        internal static string LaunchDate_Text {
            get {
                return ResourceManager.GetString("LaunchDate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        internal static string Launch_Text {
            get {
                return ResourceManager.GetString("Launch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu_Text {
            get {
                return ResourceManager.GetString("Menu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_Text {
            get {
                return ResourceManager.GetString("Name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string Node_Text {
            get {
                return ResourceManager.GetString("Node.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal_Text {
            get {
                return ResourceManager.GetString("Normal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No_Text {
            get {
                return ResourceManager.GetString("No.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating.
        /// </summary>
        internal static string Operating_Text {
            get {
                return ResourceManager.GetString("Operating.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationTime.
        /// </summary>
        internal static string OperationTime_Text {
            get {
                return ResourceManager.GetString("OperationTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Tips.
        /// </summary>
        internal static string OperationTips_Text {
            get {
                return ResourceManager.GetString("OperationTips.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Structure.
        /// </summary>
        internal static string OrganizationalStructure_Text {
            get {
                return ResourceManager.GetString("OrganizationalStructure.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        internal static string Overdue_Text {
            get {
                return ResourceManager.GetString("Overdue.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending_Text {
            get {
                return ResourceManager.GetString("Pending.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print People.
        /// </summary>
        internal static string PrintPeople_Text {
            get {
                return ResourceManager.GetString("PrintPeople.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process_Text {
            get {
                return ResourceManager.GetString("Process.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        internal static string Prompt_Text {
            get {
                return ResourceManager.GetString("Prompt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report_Text {
            get {
                return ResourceManager.GetString("Report.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve approval.
        /// </summary>
        internal static string RetrieveApproval_Text {
            get {
                return ResourceManager.GetString("RetrieveApproval.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send revocation.
        /// </summary>
        internal static string SendRevocation_Text {
            get {
                return ResourceManager.GetString("SendRevocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (kb).
        /// </summary>
        internal static string Sizekb_Text {
            get {
                return ResourceManager.GetString("Sizekb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        internal static string Sponsor_Text {
            get {
                return ResourceManager.GetString("Sponsor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Staff_Text {
            get {
                return ResourceManager.GetString("Staff.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status_Text {
            get {
                return ResourceManager.GetString("Status.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        internal static string Tel_Text {
            get {
                return ResourceManager.GetString("Tel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process can be initiated.
        /// </summary>
        internal static string TheProcessCanBeInitiated_Text {
            get {
                return ResourceManager.GetString("TheProcessCanBeInitiated.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The term.
        /// </summary>
        internal static string TheTerm_Text {
            get {
                return ResourceManager.GetString("TheTerm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title_Text {
            get {
                return ResourceManager.GetString("Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To node.
        /// </summary>
        internal static string ToNode_Text {
            get {
                return ResourceManager.GetString("ToNode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMP Workflow Management.
        /// </summary>
        internal static string TopMenu_Text {
            get {
                return ResourceManager.GetString("TopMenu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajectories.
        /// </summary>
        internal static string Trajectories_Text {
            get {
                return ResourceManager.GetString("Trajectories.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Transfer_Text {
            get {
                return ResourceManager.GetString("Transfer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type_Text {
            get {
                return ResourceManager.GetString("Type.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuspend.
        /// </summary>
        internal static string Unsuspend_Text {
            get {
                return ResourceManager.GetString("Unsuspend.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming work.
        /// </summary>
        internal static string UpcomingWork_Text {
            get {
                return ResourceManager.GetString("UpcomingWork.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string Uploaded_Text {
            get {
                return ResourceManager.GetString("Uploaded.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload people.
        /// </summary>
        internal static string UploadPeople_Text {
            get {
                return ResourceManager.GetString("UploadPeople.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string UserLogin_Text {
            get {
                return ResourceManager.GetString("UserLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ccflow  Official Website.
        /// </summary>
        internal static string website_Text {
            get {
                return ResourceManager.GetString("website.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for choosing ccflow!!  See more documents detours , Learn ccflow Lifetime benefit ..
        /// </summary>
        internal static string welcome_Text {
            get {
                return ResourceManager.GetString("welcome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When used.
        /// </summary>
        internal static string WhenUsed_Text {
            get {
                return ResourceManager.GetString("WhenUsed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work reminders.
        /// </summary>
        internal static string WorkReminders_Text {
            get {
                return ResourceManager.GetString("WorkReminders.Text", resourceCulture);
            }
        }
    }
}
