//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------



public partial class AppDemo_Login1 {
    
    /// <summary>
    /// Head1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    
    /// <summary>
    /// Form1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
    
    /// <summary>
    /// Lab1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::BP.Web.Controls.Lab Lab1;
    
    /// <summary>
    /// TB_No  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::BP.Web.Controls.TB TB_No;
    
    /// <summary>
    /// Lab2  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::BP.Web.Controls.Lab Lab2;
    
    /// <summary>
    /// TB_Pass  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::BP.Web.Controls.TB TB_Pass;
    
    /// <summary>
    /// IsRemember  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.WebControls.CheckBox IsRemember;
    
    /// <summary>
    /// Btn1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::BP.Web.Controls.Btn Btn1;
}
