//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCFlow.WF.Comm.RefFunc {
    
    
    public partial class Dot2Dot {
        
        /// <summary>
        /// RefLeft1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCFlow.WF.Comm.RefFunc.RefLeft RefLeft1;
        
        /// <summary>
        /// Dot2Dot1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCFlow.WF.Comm.RefFunc.Dot2Dot_UC Dot2Dot1;
    }
}
