//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------



public partial class SDKFlows_MyForm {
    
    /// <summary>
    /// Pub1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::SDKFlows_Pub Pub1;
}
