//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------

namespace CCFlow.SDKFlowDemo {
    
    
    public partial class TestCond {
    }
}
