//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------

namespace CCFlow.WF.CCForm {
    
    
    public partial class PointOffice {
        
        /// <summary>
        /// form1  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// Button3  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Button3;
        
        /// <summary>
        /// TB_User  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText TB_User;
        
        /// <summary>
        /// TB_FileType  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText TB_FileType;
        
        /// <summary>
        /// TB_FilePath  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText TB_FilePath;
        
        /// <summary>
        /// TB_IsReadOnly  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText TB_IsReadOnly;
        
        /// <summary>
        /// TB_IsPrint  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText TB_IsPrint;
        
        /// <summary>
        /// Button1  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Button1;
        
        /// <summary>
        /// Button2  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Button2;
        
        /// <summary>
        /// Btn_ProDoc  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Btn_ProDoc;
        
        /// <summary>
        /// Btn_UnProDoc  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Btn_UnProDoc;
        
        /// <summary>
        /// TB_Track  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText TB_Track;
        
        /// <summary>
        /// Btn_AttachDoc  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Btn_AttachDoc;
        
        /// <summary>
        /// Btn_UnAttachDoc  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Btn_UnAttachDoc;
        
        /// <summary>
        /// Btn_Save  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Btn_Save;
        
        /// <summary>
        /// sShowName  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect sShowName;
        
        /// <summary>
        /// Button4  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton Button4;
    }
}
