//------------------------------------------------------------------------------
// <auto-generated>
//      This code is generated by the tool .
//      Runtime version :4.0.30319.296
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost .
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingApp.Properties {
    using System;
    
    
    /// <summary>
    ///    A strongly typed resource class , Used to find localized strings, etc. .
    /// </summary>
    //  Such is the  StronglyTypedResourceBuilder
    //  Classes like  ResGen 或 Visual Studio  The tool automatically generates the .
    //  To add or remove members , Please edit  .ResX  File , Then re-run  ResGen
    // (以 /str  As the command options ), Or rebuild  VS  Project .
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///    Return to such use of cache  ResourceManager  Examples .
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Use this strongly typed resource class , Find resources for all 
        ///    Rewrite the current thread  CurrentUICulture  Property .
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
