//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------



public partial class AppDemo_Lef1t {
    
    /// <summary>
    /// Head1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
    
    /// <summary>
    /// Ul1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Ul1;
    
    /// <summary>
    /// Li2s  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li2s;
    
    /// <summary>
    /// get  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl get;
    
    /// <summary>
    /// Li1  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li1;
    
    /// <summary>
    /// Li3  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li3;
    
    /// <summary>
    /// Li7  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li7;
    
    /// <summary>
    /// Li8  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li8;
    
    /// <summary>
    /// Li5  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li5;
    
    /// <summary>
    /// over  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl over;
    
    /// <summary>
    /// Li2  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li2;
    
    /// <summary>
    /// Li6  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li6;
    
    /// <summary>
    /// end  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl end;
    
    /// <summary>
    /// Li4  Controls .
    /// </summary>
    /// <remarks>
    ///  Automatically generated fields .
    ///  To make changes , Move field declaration from designer code-behind file file .
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl Li4;
}
