//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------

namespace CCFlow.WF.Admin.Templete {
    
    
    public partial class Uploade {
        
        /// <summary>
        /// Btn_Upload  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_Upload;
    }
}
