using System;
using System.Data;
using BP.DA;
using BP.En;
using BP.WF;

namespace BP.WF.Data
{
    /// <summary>
    ///  Type generated 
    /// </summary>
    public enum BillFileType
    {
        /// <summary>
        /// Word
        /// </summary>
        Word=0,
        PDF=1,
        Excel=2,
        Html=3,
        RuiLang=5
    }
    /// <summary>
    ///  Document template properties 
    /// </summary>
    public class BillTemplateAttr:BP.En.EntityNoNameAttr
    {
        public const string Url = "Url";
        /// <summary>
        /// NodeID
        /// </summary>
        public const string NodeID = "NodeID";
        /// <summary>
        ///  The need for service 
        /// </summary>
        public const string IsNeedSend = "IsNeedSend";
        /// <summary>
        ///  Use to generate documents 
        /// </summary>
        public const string IDX = "IDX";
        /// <summary>
        ///  To exclude the field 
        /// </summary>
        public const string ExpField = "ExpField";
        /// <summary>
        ///  To replace the value 
        /// </summary>
        public const string ReplaceVal = "ReplaceVal";
        /// <summary>
        ///  Document Type 
        /// </summary>
        public const string FK_BillType = "FK_BillType";
        /// <summary>
        ///  Whether to generate PDF
        /// </summary>
        public const string BillFileType = "BillFileType";
    }
	/// <summary>
	///  Document templates 
	/// </summary>
	public class BillTemplate : EntityNoName
    {
        #region   Property 
        /// <summary>
        ///  Document Type 
        /// </summary>
        public string FK_BillType
        {
            get
            {
                return this.GetValStringByKey(BillTemplateAttr.FK_BillType);
            }
            set
            {
                this.SetValByKey(BillTemplateAttr.FK_BillType, value);
            }
        }
        /// <summary>
        ///  To replace the value 
        /// </summary>
        public string ReplaceVal
        {
            get
            {
                return this.GetValStringByKey(BillTemplateAttr.ReplaceVal);
            }
            set
            {
                this.SetValByKey(BillTemplateAttr.ReplaceVal, value);
            }
        }
        /// <summary>
        /// UI Access control interface 
        /// </summary>
        public override UAC HisUAC
        {
            get
            {
                UAC uac = new UAC();
                uac.OpenForSysAdmin();
                return uac;
            }
        }
        /// <summary>
        ///  Serial number 
        /// </summary>
        public new string No
        {
            get
            {
                string no = this.GetValStrByKey("No");
                no = no.Replace("\n", "");
                no = no.Replace(" ", "");
                return no;
            }
            set
            {
                this.SetValByKey("No", value);
                this.SetValByKey(BillTemplateAttr.Url, value);
            }
        }
        /// <summary>
        ///  Generated by document type 
        /// </summary>
        public BillFileType HisBillFileType
        {
            get
            {
                return (BillFileType)this.GetValIntByKey(BillTemplateAttr.BillFileType);
            }
            set
            {
                this.SetValByKey(BillTemplateAttr.BillFileType, (int)value);
            }
        }
        /// <summary>
        ///  Open connections 
        /// </summary>
        public string Url
        {
            get
            {
                string s= this.GetValStrByKey(BillTemplateAttr.Url);
                if (s == "" || s == null)
                    return this.No;
                return s;
            }
            set
            {
                this.SetValByKey(BillTemplateAttr.Url, value);
            }
        }
        /// <summary>
        ///  Node Name 
        /// </summary>
        public string NodeName
        {
            get
            {
                Node nd = new Node(this.NodeID);
                return nd.Name;
            }
        }
        /// <summary>
        ///  Node ID
        /// </summary>
        public int NodeID
        {
            get
            {
                return this.GetValIntByKey(BillTemplateAttr.NodeID);
            }
            set
            {
                this.SetValByKey(BillTemplateAttr.NodeID, value);
            }
        }
        /// <summary>
        ///  The need for service 
        /// </summary>
        public bool IsNeedSend_del
        {
            get
            {
                return this.GetValBooleanByKey(BillTemplateAttr.IsNeedSend); 
            }
        }
        #endregion

        #region  Constructor 
        /// <summary>
        ///  Document templates 
		/// </summary>
		public BillTemplate(){}
        public BillTemplate(string no):base(no.Replace( "\n","" ).Trim() ) 
        {
        }
		/// <summary>
		///  Override the base class methods 
		/// </summary>
        public override Map EnMap
        {
            get
            {
                if (this._enMap != null)
                    return this._enMap;
                Map map = new Map("WF_BillTemplate");
                map.EnDesc = " Document templates "; // " Document templates ";
                map.EnType = EnType.Admin;
                map.DepositaryOfEntity = Depositary.None;
                map.DepositaryOfMap = Depositary.Application;
                map.CodeStruct = "6";

                map.AddTBStringPK(BillTemplateAttr.No, null, "No", true, false, 1, 300, 6);
                map.AddTBString(BillTemplateAttr.Name, null, "Name", true, false, 0, 200, 20);
                map.AddTBString(BillTemplateAttr.Url, null, "URL", true, false, 0, 200, 20);
                map.AddTBInt(BillTemplateAttr.NodeID, 0, "NodeID", true, false);

                map.AddDDLSysEnum(BillTemplateAttr.BillFileType, 0, " Generated file type ", true, false,
                    "BillFileType","@0=Word@1=PDF@2=Excel( Unfinished )@3=Html( Unfinished )@5= Sharp wave reports ");

                map.AddTBString(BillTemplateAttr.FK_BillType, null, " Document Type ", true, false, 0, 4, 4);

                map.AddTBString("IDX", null, "IDX", false, false, 0, 200, 20);
                map.AddTBString(BillTemplateAttr.ExpField, null, " To exclude the field ", false, false, 0, 800, 20);
                map.AddTBString(BillTemplateAttr.ReplaceVal, null, " To replace the value ", false, false, 0, 3000, 20);
                this._enMap = map;
                return this._enMap;
            }
        }
		#endregion 
	}
	/// <summary>
    ///  Document templates s
	/// </summary>
	public class BillTemplates: EntitiesNoName
	{
		#region  Structure 
		/// <summary>
		///  Get it  Entity 
		/// </summary>
		public override Entity GetNewEntity
		{
			get
			{
				return new BillTemplate();
			}
		}
		/// <summary>
		///  Document templates 
		/// </summary>
        public BillTemplates()
        {
        }
		#endregion

        #region  Query and structure 
        /// <summary>
        ///  By node query 
        /// </summary>
        /// <param name="nd"></param>
        public BillTemplates(Node nd)
        {
            QueryObject qo = new QueryObject(this);
            qo.AddWhere(BillTemplateAttr.NodeID, nd.NodeID);
            if (nd.IsStartNode)
            {
                qo.addOr();
                qo.AddWhere("No", "SLHZ");
            }
            qo.DoQuery();
        }
        /// <summary>
        ///  By the process queries 
        /// </summary>
        /// <param name="fk_flow"> Process ID </param>
        public BillTemplates(string fk_flow)
        {
            QueryObject qo = new QueryObject(this);
            qo.AddWhereInSQL(BillTemplateAttr.NodeID, "SELECT NodeID FROM WF_Node WHERE fk_flow='" + fk_flow + "'");
            qo.DoQuery();
        }
        /// <summary>
        ///  By node query 
        /// </summary>
        /// <param name="fk_node"> Node ID</param>
        public BillTemplates(int fk_node)
        {
            QueryObject qo = new QueryObject(this);
            qo.AddWhere(BillTemplateAttr.NodeID, fk_node);
            qo.DoQuery();
        }
        #endregion  Query and structure 

    }
	
}
