//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------

namespace CCFlow.WF.MapDef.Rpt {
    
    
    public partial class S7_PowerFlowDeptEmp {
        
        /// <summary>
        /// DDL_DeptPowerType  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDL_DeptPowerType;
        
        /// <summary>
        /// Pub2  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::WF_MapDef_Pub Pub2;
        
        /// <summary>
        /// Btn_Save  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_Save;
        
        /// <summary>
        /// Btn_SaveAndNext  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_SaveAndNext;
        
        /// <summary>
        /// Btn_Close  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_Close;
    }
}
