//------------------------------------------------------------------------------
// < Automatic generation >
//      This code is generated by the tool .
//
//      Changes to this file may cause incorrect behavior , And if 
//      Regenerate code , These changes will be lost . 
// </ Automatic generation >
//------------------------------------------------------------------------------

namespace CCFlow.SDKFlowDemo.TeleCom._3SheBei {
    
    
    public partial class S4_FangAnShiShi {
        
        /// <summary>
        /// Btn_Send  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_Send;
        
        /// <summary>
        /// Btn_Save  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_Save;
        
        /// <summary>
        /// Btn_Return  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_Return;
        
        /// <summary>
        /// Btn_Track  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_Track;
        
        /// <summary>
        /// Btn_Forward  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btn_Forward;
        
        /// <summary>
        /// TB_NextWorker  Controls .
        /// </summary>
        /// <remarks>
        ///  Automatically generated fields .
        ///  To make changes , Move field declaration from designer code-behind file file .
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TB_NextWorker;
    }
}
